### ISSUE TITLE
Code could be shorter in app/Http/Middleware/FindOrCreateCart.php

### ISSUE THREAD

**Issue by ipontt** [raynirola/sikkim.store#4]
https://github.com/raynirola/sikkim.store/blob/b8246eca98c709a13b5dc6ad27c35d8dbc51a8c4/app/Http/Middleware/FindOrCreateCart.php#L18-L30

Using `firstOrCreate()`, you can remove the verification you do with `exists()`.
```php
$cart = $request->user('user')->carts()->firstOrCreate(['store_id' => $request->store->id]);

$request->merge(['cart' => $cart]);
```

**Comment by raynirola** [comment]
Nice, Thanks.
